Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
todos.Todo: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the TodosConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).
July 21, 2023 - 10:51:06
Django version 4.2.3, using settings 'todoApp.settings'
Starting development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.

Invalid HTTP_HOST header: '35.175.115.227:8001'. You may need to add '35.175.115.227' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.175.115.227:8001'. You may need to add '35.175.115.227' to ALLOWED_HOSTS.
Bad Request: /
[21/Jul/2023 10:51:18] "GET / HTTP/1.1" 400 63244
Invalid HTTP_HOST header: '35.175.115.227:8001'. You may need to add '35.175.115.227' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.175.115.227:8001'. You may need to add '35.175.115.227' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[21/Jul/2023 10:51:19] "GET /favicon.ico HTTP/1.1" 400 63217
/home/ubuntu/projects/django-todo/todoApp/settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
todos.Todo: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the TodosConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).
July 21, 2023 - 10:52:25
Django version 4.2.3, using settings 'todoApp.settings'
Starting development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.

[21/Jul/2023 10:52:29] "GET / HTTP/1.1" 302 0
[21/Jul/2023 10:52:29] "GET /todos HTTP/1.1" 301 0
[21/Jul/2023 10:52:30] "GET /todos/ HTTP/1.1" 200 3515
[21/Jul/2023 10:52:30] "GET /static/css/style.css HTTP/1.1" 200 225
Not Found: /favicon.ico
[21/Jul/2023 10:52:31] "GET /favicon.ico HTTP/1.1" 404 2575
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
todos.Todo: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the TodosConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).
[21/Jul/2023 11:11:10] "GET /todos/ HTTP/1.1" 200 3515
